# Generated by Django 3.1.3 on 2022-07-25 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('tool_num', models.CharField(max_length=200)),
                ('raw_image', models.CharField(max_length=200)),
                ('processed_image', models.CharField(max_length=200)),
                ('wear_area', models.FloatField(default=0.0)),
                ('wear_length', models.FloatField(default=0.0)),
                ('vb_max', models.FloatField(default=0.0)),
                ('vb_mean', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ToolWear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wear_area', models.FloatField(default=0.0)),
                ('wear_length', models.FloatField(default=0.0)),
                ('vb_max', models.FloatField(default=0.0)),
                ('vb_mean', models.FloatField(default=0.0)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atwdm.tool')),
            ],
        ),
    ]
